%YAML:1.0

imu0:
  T_i_b:
   - [1.0, 0.0, 0.0, 0.0]
   - [0.0, 1.0, 0.0, 0.0]
   - [0.0, 0.0, 1.0, 0.0]
   - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 0.0014676097691831726
  accelerometer_random_walk: 7.503959876866583e-05
  gyroscope_noise_density: 8.801364198823276e-05
  gyroscope_random_walk: 2.7696084253591647e-07
  rostopic: /zed/zed_node/imu/data_raw
  time_offset: 0.0
  update_rate: 400.0
  # three different modes supported:
  # "calibrated" (same as "kalibr"), "kalibr", "rpng"
  model: "kalibr"
  # how to get from Kalibr imu.yaml result file:
  #   - Tw is imu0:gyroscopes:M:
  #   - R_IMUtoGYRO: is imu0:gyroscopes:C_gyro_i:
  #   - Ta is imu0:accelerometers:M:
  #   - R_IMUtoACC not used by Kalibr
  #   - Tg is imu0:gyroscopes:A:
  Tw:
   - [1.0121566974186789, 0.0, 0.0]
   - [0.003502789928499193, 1.0377907903773864, 0.0]
   - [-0.002350800041734941, 0.0034563370162959896, 0.9910612079615594]
  R_IMUtoGYRO:
   - [0.9999400197137405, 0.010252400931625891, -0.003852953415637433]
   - [-0.010240213455774668, 0.99994254393225, 0.00316967864017436]
   - [0.003885228856328422, -0.003130033456530886, 0.9999875538661951]
  Ta:
   - [1.0065946087415696, 0.0, 0.0]
   - [-0.010573480229415184, 1.0009327644516486, 0.0]
   - [0.0024210830464391053, -0.0031069906815682047, 1.0050497161444607]
  R_IMUtoACC:
   - [ 1.0, 0.0, 0.0 ]
   - [ 0.0, 1.0, 0.0 ]
   - [ 0.0, 0.0, 1.0 ]
  Tg:
   - [-5.650048764743075e-06, -0.0003082718996754436, -6.4444934716435956e-06]
   - [0.00040109102051176754, 4.0285754374909685e-05, 0.0028775268666581416]
   - [-0.00019292908920397485, -0.0012419210320457966, -7.739568223222876e-05]
