%YAML:1.0

cam0:
  T_cam_imu:
   - [0.00886125341411162, -0.9998945175584373, -0.01150790791198597, 0.007825085097709001]
   - [-0.013611205705413132, 0.01138668447771865, -0.9998425268490283, -0.0026680464222245096]
   - [0.9998680979345105, 0.009016494506443984, -0.01350886966549908, -0.061814929113247964]
   - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [-0.07435614096320153, 0.0350724142199148, 7.446584565103861e-05, -0.00037952727798445983]
  distortion_model: radtan
  intrinsics: [518.2634318231645, 519.7251461821156, 491.12091628689495, 298.889614400566]
  resolution: [960, 540]
  rostopic: /zed/zed_node/left_raw_gray/image_raw_gray
  timeshift_cam_imu: 0.010012502401340325
cam1:
  T_cam_imu:
   - [0.012342749003059122, -0.9998869960338269, -0.008582057416355371, -0.11204002620947265]
   - [-0.015583864375975476, 0.008389313499572643, -0.9998433690284281, -0.0028376664038867925]
   - [0.9998023803323131, 0.012474557365134198, -0.015478556146659384, -0.06092239411020339]
   - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
   - [0.9999896592653807, -0.002972691460129763, 0.003441579257267502, -0.11966022069104226]
   - [0.0029795842714804167, 0.9999935621921365, -0.001999412874875427, -0.0003165462236411807]
   - [-0.0034356134634630927, 0.0020096466749015083, 0.9999920789088108, 0.0009242911596897496]
   - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [-0.0752236689208371, 0.0363764814241836, -0.0002099870880507369, -0.0011496844914582194]
  distortion_model: radtan
  intrinsics: [518.9887853850768, 520.2619502541255, 500.4489094151987, 279.81090527392683]
  resolution: [960, 540]
  rostopic: /zed/zed_node/right_raw_gray/image_raw_gray
  timeshift_cam_imu: 0.009092943670607114
