%YAML:1.0 # need to specify the file type at the top!

wheel:
  noise_w: 0.2
  noise_v: 0.5
  noise_p: 0.1
  chi2_mult: 2
  timeoffset: 0.0
  intrinsics: [0.3, 0.3, 1.5]
  reuse_of_information: false
  T_imu_wheel:
    - [1.0, 0.0, 0.0, 0.07]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, -1.7]
    - [0.0, 0.0, 0.0, 1.0]
  topic: "/wheel_odom"